services:
  db:
    image: postgres:14-alpine
    env_file: .env

  app:
    build: .
    image: dinopedia
    env_file: .env
    depends_on:
    - db

  nginx:
    image: nginx:1.25.5
    ports: 
    - 80:80
    volumes:
    - ./api_gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
    - app
