# Generated by Django 5.0.7 on 2024-07-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dinosaur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('eating_classification', models.CharField(choices=[('H', 'Herbivore'), ('O', 'Omnivore'), ('C', 'Carnivore'), ('U', 'Unknown')], default='U', max_length=1)),
                ('typical_color', models.CharField(max_length=50)),
                ('period', models.CharField(choices=[('T', 'Triassic'), ('J', 'Jurassic'), ('C', 'Cretaceous'), ('P', 'Paleogene'), ('N', 'Neogene'), ('U', 'Unknown')], default='U', max_length=1)),
                ('average_size', models.CharField(choices=[('XXS', 'Tiny'), ('XS', 'Very small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Very large'), ('XXL', 'Gigantic'), ('U', 'Unknown')], default='U', max_length=3)),
            ],
        ),
    ]
