# Generated by Django 5.0.7 on 2024-07-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinosaur',
            name='image1',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='dinosaur',
            name='image2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
