# Generated by Django 5.0.7 on 2024-08-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_dinosaurs',
            field=models.ManyToManyField(to='dinosaurs.dinosaur'),
        ),
    ]
