# Generated by Django 5.0.7 on 2024-07-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0002_dinosaur_image1_dinosaur_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinosaur',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='dinosaur',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
