# Generated by Django 5.0.7 on 2024-07-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0003_alter_dinosaur_image1_alter_dinosaur_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinosaur',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
