# Generated by Django 5.0.7 on 2024-07-31 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0004_alter_dinosaur_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dinosaur',
            options={'ordering': ['name']},
        ),
    ]
